[package]
name = "schedule-m8"
version = "0.1.0"
authors = ["'AGhost-7' <'jonathan.boudreau.92@gmail.com'>"]

[dependencies]
sled = '*'
priority-queue = '*'
rmp-serde = '*'
warp = '0.1'
hyper = '0.12'
futures = { version = "0.3", features = ["compat"] }
serde_derive = '*'
serde = '*'
serde_json = '*'
uuid = { version = '*', features = ['serde', 'v4'] }
